// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationMode } from "../CollaborationMode";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { UserInput } from "./UserInput";

/**
 * The bounded initial-turn surface used by Empatra's atomic thread creation RPCs.
 */
export type EmpatraInitialTurnParams = { clientUserMessageId?: string | null, input: Array<UserInput>, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandboxPolicy?: SandboxPolicy | null, permissions?: string | null, model?: string | null, effort?: ReasoningEffort | null, collaborationMode?: CollaborationMode | null, };
