// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnWorkSwarmCommunicationKind } from "./TurnWorkSwarmCommunicationKind";
import type { TurnWorkSwarmCommunicationStatus } from "./TurnWorkSwarmCommunicationStatus";

export type TurnWorkSwarmCommunicationMessage = { id: string, senderAgentPath: string, recipientAgentPath: string, senderTaskId?: string, recipientTaskId?: string, kind: TurnWorkSwarmCommunicationKind, topic?: string, status: TurnWorkSwarmCommunicationStatus, preview?: string, contentRedacted: boolean, createdAtMs: bigint, updatedAtMs: bigint, correlationId?: string, inReplyTo?: string, };
