// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnWorkSwarmCommunicationMessage } from "./TurnWorkSwarmCommunicationMessage";

export type TurnWorkSwarmCommunicationProgress = { queued: bigint, delivered: bigint, acked: bigint, expired: bigint, deadLettered: bigint, cancelled: bigint, messages: Array<TurnWorkSwarmCommunicationMessage>, messagesTruncated: boolean, };
