// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnWorkSwarmCommunicationProgress } from "./TurnWorkSwarmCommunicationProgress";
import type { TurnWorkSwarmProgressStatus } from "./TurnWorkSwarmProgressStatus";
import type { TurnWorkSwarmTaskProgress } from "./TurnWorkSwarmTaskProgress";

export type TurnWorkSwarmProgressNotification = { threadId: string, turnId: string, runId: string, status: TurnWorkSwarmProgressStatus, title?: string, maxConcurrency: bigint, runtimeUsedSeconds: bigint, runtimeBudgetSeconds?: bigint, total: bigint, queued: bigint, running: bigint, succeeded: bigint, failed: bigint, cancelled: bigint, skipped: bigint, tokensUsed: bigint, tokenBudget?: bigint, taskId?: string, agentPath?: string, model?: string, fallbackReason?: string, error?: string, tasks: Array<TurnWorkSwarmTaskProgress>, communication: TurnWorkSwarmCommunicationProgress, };
