// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnWorkSwarmTaskKind } from "./TurnWorkSwarmTaskKind";
import type { TurnWorkSwarmTaskStatus } from "./TurnWorkSwarmTaskStatus";

export type TurnWorkSwarmTaskProgress = { id: string, kind: TurnWorkSwarmTaskKind, specialist?: string, status: TurnWorkSwarmTaskStatus, summary?: string, dependsOn: Array<string>, attempt: bigint, maxAttempts: bigint, tokensUsed: bigint, model?: string, fallbackReason?: string, agentPath?: string, error?: string, };
