// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnWorkSwarmProgressStatus } from "./TurnWorkSwarmProgressStatus";

export type TurnWorkSwarmProgressNotification = { threadId: string, turnId: string, runId: string, status: TurnWorkSwarmProgressStatus, total: bigint, queued: bigint, running: bigint, succeeded: bigint, failed: bigint, cancelled: bigint, skipped: bigint, tokensUsed: bigint, tokenBudget?: bigint, taskId?: string, agentPath?: string, model?: string, fallbackReason?: string, error?: string, };
