// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-specific reasoning effort identifier.
 *
 * Codex has a few canonical efforts, but remote catalogs can expose provider-specific strings.
 */
export type ReasoningEffort = string;
